### PR TITLE
Add PHP7 for travis

### PR DESCRIPTION
**Pull request by indytechcook**
[Review on Reviewable](https://reviewable.io/reviews/uecode/segment-io-php/6)

### CODE REVIEW

**Comment by kmfk** [comment]
@indytechcook - I think its safe to set the php version to `>=5.4`

**Comment by indytechcook** [comment]
Sorry to make the commit log messy.

**Comment by kmfk** [comment]
No worries, you can always rebase to clean up the commits if it bothers you.  

I tried rebuilding the test on travis - it seems like its ignoring the recent composer.json change.

**Comment by indytechcook** [comment]
I tried to run composer update to see if travis just looks at the lock file but ran into another dependency issue:

```
  Problem 1
    - Installation request for mockery/mockery dev-master -> satisfiable by mockery/mockery[dev-master].
    - mockery/mockery dev-master requires hamcrest/hamcrest-php ^2.0@dev -> no matching package found.
```

**Comment by kmfk** [comment]
oh jeez.  never meant to include the lock file in the first place. feel free to nuke that.

Should be able to fix the dependencies by fixing the versions on a couple of those dev dependencies:

```
"mockery/mockery":    "~0.9.4",                                         
"phpunit/phpunit":    "~4.0",                                           
"raulfraile/ladybug": "~1.0.13" 
```

**Comment by kmfk** [comment]
let me know, I don't mind doing a separate PR to fix those issues

**Pull request closed without merging**
